// Code generated by tedi; DO NOT EDIT.

package auto

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("unit")
	t.TestLabel("integration")
	t.TestLabel("regression")

	// Fixtures:
	t.Fixture(fixture_nameLength)
	t.Fixture(fixture_rand)
	t.Fixture(fixture_timer)

	// Before tests:
	t.BeforeTest(pre_print, "unit")

	// Tests:
	t.Test("test_timer", test_timer, "unit")
	t.Test("test_withSub", test_withSub, "unit")
	t.Test("integration_withFoo", integration_withFoo, "integration")
	t.Test("integration_simple", integration_simple, "integration")
	t.Test("test_withSleep", test_withSleep, "unit")

	os.Exit(t.Run())
}
