// Code generated by tedi; DO NOT EDIT.

package test

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("integration")
	t.TestLabel("test")

	// Fixtures:
	t.Fixture(myFixture)
	t.Fixture(myTimer)

	// OnceFixtures:
	t.OnceFixture(randFixture)

	// Before tests:
	t.BeforeTest(myBefore, "test")

	// Tests:
	t.Test("MyTest2", MyTest2, "test")
	t.Test("MyTest3", MyTest3, "test")
	t.Test("MyIntegrationTest", MyIntegrationTest, "integration")
	t.Test("integration_Test", integration_Test, "integration")
	t.Test("MyTestTiming", MyTestTiming, "test")

	os.Exit(t.Run())
}
