// Code generated by "tedi "; DO NOT EDIT.

package test

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// Fixtures:
	t.Fixture(myFixture)
	t.Fixture(myTimer)

	// OnceFixtures:
	t.OnceFixture(randFixture)

	// Before tests:
	t.BeforeTest(myBefore)

	// Tests:
	t.Test("MyTest2", MyTest2)
	t.Test("MyTest3", MyTest3)
	t.Test("MyTestTiming", MyTestTiming)

	os.Exit(t.Run())
}
