// Code generated by "tedi generate ./example/"; DO NOT EDIT.

package tedi

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("test")

	os.Exit(t.Run())
}
