// Code generated by tedi; DO NOT EDIT.

package labels

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("unit")
	t.TestLabel("integration")
	t.TestLabel("regression")

	// Fixtures:
	t.Fixture(myFixture)
	t.Fixture(myTimer)

	// OnceFixtures:
	t.OnceFixture(randFixture)

	// Before tests:
	t.BeforeTest(myBefore, "unit")

	// Tests:
	t.Test("MyTest", MyTest, "unit")
	t.Test("AnotherTest", AnotherTest, "unit")
	t.Test("MyIntegrationTest", MyIntegrationTest, "integration")
	t.Test("MyTestTiming", MyTestTiming, "unit")

	os.Exit(t.Run())
}
